name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd tests
        pip install black
        pip install -r requirements.txt

    - name: Lint with Black
      run: |
        black . --diff --check --color
    
    - name: Test with pytest
      run: |
        cd tests
        pytest . -v